export FG_RESET="\e[0m"
export FG_RED="\e[31m"
export FG_GREEN="\e[32m"
export FG_YELLOW="\e[33m"
export FG_BLUE="\e[34m"
export FG_MAGENTA="\e[35m"
export FG_CYAN="\e[36m"
export FG_LIGHT_GREY="\e[37m"
